apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: phptools
  name: phptools
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: phptools
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        name: phptools
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
